steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "${_IMAGE_NAME}",
         "--build-arg", "ENV_NAME=$_ENV_NAME", "siivagunnerdb"]

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "${_IMAGE_NAME}"]

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "${_IMAGE_NAME}",
         "-s", "${_INSTANCE_NAME}",
         "--", "python", "manage.py", "deleterevisions"]

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "${_IMAGE_NAME}",
         "-s", "${_INSTANCE_NAME}",
         "--", "python", "manage.py", "migrate"]

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "${_IMAGE_NAME}",
         "-s", "${_INSTANCE_NAME}",
         "--", "python", "manage.py", "collectstatic", "--no-input"]

substitutions:
    _IMAGE_NAME: "gcr.io/${PROJECT_ID}/siivagunnerdb-${_ENV_NAME}"
    _INSTANCE_NAME: "${PROJECT_ID}:us-central1:myinstance"

options:
    dynamic_substitutions: true
    logging: "CLOUD_LOGGING_ONLY"
