steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "siivagunnerdb"]

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
         "-s", "${PROJECT_ID}:us-central1:myinstance",
         "--", "python", "manage.py", "migrate", "--settings=siivagunnerdb.${_SETTINGS}"]

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
         "-s", "${PROJECT_ID}:us-central1:myinstance",
         "--", "python", "manage.py", "collectstatic", "--no-input", "--settings=siivagunnerdb.${_SETTINGS}"]
