# Generated by Django 3.1.7 on 2021-03-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0008_auto_20210307_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rip',
            name='uploadDate',
            field=models.DateTimeField(blank=True, default='Unknown'),
        ),
    ]
