# Generated by Django 3.1.7 on 2021-03-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0010_auto_20210307_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rip',
            name='uploadDate',
            field=models.DateTimeField(),
        ),
    ]
