# Generated by Django 3.2.4 on 2021-11-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0021_auto_20211119_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rip',
            name='videoId',
        ),
        migrations.AlterField(
            model_name='rip',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
