# Generated by Django 3.2.4 on 2022-08-01 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0015_auto_20220731_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnails', models.JSONField(blank=True, default='')),
                ('channelTitle', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default='')),
                ('categoryId', models.CharField(blank=True, default='', max_length=50)),
                ('liveBroadcastContent', models.CharField(blank=True, default='', max_length=20)),
                ('defaultLanguage', models.CharField(blank=True, default='', max_length=50)),
                ('localized', models.JSONField(blank=True, default='')),
                ('defaultAudioLanguage', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('dimension', models.CharField(blank=True, default='', max_length=20)),
                ('definition', models.CharField(blank=True, default='', max_length=20)),
                ('caption', models.CharField(blank=True, default='', max_length=20)),
                ('licensedContent', models.BooleanField(blank=True, default=False)),
                ('regionRestriction', models.JSONField(blank=True, default='')),
                ('contentRating', models.JSONField(blank=True, default='')),
                ('projection', models.CharField(blank=True, default='', max_length=20)),
                ('viewCount', models.PositiveIntegerField()),
                ('likeCount', models.PositiveIntegerField()),
                ('dislikeCount', models.PositiveIntegerField()),
                ('favoriteCount', models.PositiveIntegerField()),
                ('commentCount', models.PositiveIntegerField()),
                ('wikiStatus', models.CharField(choices=[('Documented', 'Documented'), ('Undocumented', 'Undocumented')], max_length=20)),
                ('videoStatus', models.CharField(choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Unavailable', 'Unavailable'), ('Private', 'Private'), ('Deleted', 'Deleted')], max_length=20)),
                ('visible', models.BooleanField(blank=True, default=False)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='channels.channel')),
            ],
        ),
    ]
