# Generated by Django 3.2.4 on 2022-08-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
        ('channels', '0018_auto_20220818_1102'),
        ('playlists', '0004_auto_20220818_1102'),
        ('videos', '0003_auto_20220816_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='contributors',
            field=models.ManyToManyField(blank=True, default=[], to='contributors.Contributor'),
        ),
        migrations.AddField(
            model_name='video',
            name='playlists',
            field=models.ManyToManyField(blank=True, default=[], to='playlists.Playlist'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='channels.channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='commentCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislikeCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='favoriteCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='likeCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoStatus',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Unavailable', 'Unavailable'), ('Private', 'Private'), ('Deleted', 'Deleted')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='viewCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='wikiStatus',
            field=models.CharField(blank=True, choices=[('Documented', 'Documented'), ('Undocumented', 'Undocumented')], default='', max_length=20),
        ),
    ]
