# Generated by Django 3.1.14 on 2023-01-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='contentRating',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='localized',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='regionRestriction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
