# Generated by Django 3.2.18 on 2023-07-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20230115_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoStatus',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Unavailable', 'Unavailable'), ('Private', 'Private'), ('Deleted', 'Deleted')], default='Public', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='wikiStatus',
            field=models.CharField(blank=True, choices=[('Documented', 'Documented'), ('Undocumented', 'Undocumented')], default='Undocumented', max_length=20),
        ),
    ]
