# Generated by Django 4.2.17 on 2026-04-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_wikititle'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['publishedAt'], name='videos_vide_publish_47a899_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title'], name='videos_vide_title_8a2e81_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['viewCount'], name='videos_vide_viewCou_892a16_idx'),
        ),
    ]
