# Generated by Django 4.2.17 on 2026-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_videos_vide_publish_47a899_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['channel'], name='videos_vide_channel_918466_idx'),
        ),
    ]
