# Generated by Django 3.1.14 on 2022-09-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(max_length=57, primary_key=True, serialize=False),
        ),
    ]
