# Generated by Django 3.1.14 on 2022-12-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_spreadsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
