# Generated by Django 3.1.14 on 2023-01-01 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20221221_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='spreadsheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheets.spreadsheet'),
        ),
    ]
