# Generated by Django 3.1.14 on 2023-01-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_sheet_spreadsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
