# Generated by Django 3.1.7 on 2021-03-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210308_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='contact',
        ),
    ]
