# Generated by Django 3.1.7 on 2021-03-08 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.CharField(blank=True, max_length=24)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('channelStatus', models.CharField(blank=True, choices=[('Public', 'Public'), ('Deleted', 'Deleted')], max_length=20)),
                ('joinDate', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('subscriberCount', models.PositiveIntegerField(blank=True, default=0)),
                ('profilePicture', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
