# Generated by Django 3.1.7 on 2021-03-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channel_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscriberCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
