# Generated by Django 3.1.7 on 2021-03-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_channel_wiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='wiki',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
