# Generated by Django 3.1.7 on 2021-03-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_auto_20210310_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
