# Generated by Django 3.2.4 on 2021-11-20 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0012_auto_20210310_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='profilePicture',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='slug',
        ),
        migrations.AddField(
            model_name='channel',
            name='videoCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='viewCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channelId',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channelStatus',
            field=models.CharField(choices=[('Public', 'Public'), ('Deleted', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='joinDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscriberCount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='visible',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='wiki',
            field=models.CharField(max_length=100),
        ),
    ]
