# Generated by Django 3.1.7 on 2021-02-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
