# Generated by Django 3.1.7 on 2021-03-02 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='uploadDate',
            field=models.DateTimeField(),
        ),
    ]
