# Generated by Django 3.2.4 on 2022-06-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0022_auto_20211120_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rip',
            name='length',
            field=models.CharField(max_length=20),
        ),
    ]
