# Generated by Django 3.1.7 on 2021-03-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210308_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(),
        ),
    ]
