# Generated by Django 3.1.7 on 2021-03-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0007_auto_20210307_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rip',
            name='description',
            field=models.TextField(blank=True, default='Unknown'),
        ),
        migrations.AlterField(
            model_name='rip',
            name='length',
            field=models.CharField(blank=True, default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='rip',
            name='videoId',
            field=models.CharField(blank=True, default='Unknown', max_length=11),
        ),
        migrations.AlterField(
            model_name='rip',
            name='videoStatus',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Private', 'Private'), ('Deleted', 'Deleted'), ('Unavailable', 'Unavailable')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='rip',
            name='wikiStatus',
            field=models.CharField(blank=True, choices=[('Documented', 'Documented'), ('Undocumented', 'Undocumented')], default='Unknown', max_length=20),
        ),
    ]
