# Generated by Django 3.1.7 on 2021-03-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0009_auto_20210307_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rip',
            name='length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rip',
            name='uploadDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='rip',
            name='videoId',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='rip',
            name='videoStatus',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Private', 'Private'), ('Deleted', 'Deleted'), ('Unavailable', 'Unavailable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rip',
            name='wikiStatus',
            field=models.CharField(blank=True, choices=[('Documented', 'Documented'), ('Undocumented', 'Undocumented')], max_length=20),
        ),
    ]
