# Generated by Django 3.1.7 on 2021-03-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20210307_2028'),
        ('rips', '0013_auto_20210307_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='rip',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='channels.channel'),
        ),
    ]
