# Generated by Django 3.1.7 on 2021-03-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0014_rip_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rip',
            name='commentCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rip',
            name='dislikeCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rip',
            name='likeCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rip',
            name='uploadDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rip',
            name='viewCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
