# Generated by Django 3.1.7 on 2021-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0015_auto_20210308_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='rip',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
