# Generated by Django 3.1.7 on 2021-03-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0017_auto_20210308_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rip',
            name='thumbnail',
        ),
    ]
