# Generated by Django 3.1.7 on 2021-03-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0019_auto_20210308_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rip',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
