# Generated by Django 3.2.4 on 2022-08-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0018_auto_20220818_1102'),
        ('playlists', '0003_auto_20220816_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='channels.channel'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='itemCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
