# Generated by Django 3.2.4 on 2022-08-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20220818_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='publishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
