# Generated by Django 3.2.4 on 2022-08-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_alter_playlist_publishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(blank=True, default='placeholder', max_length=100),
        ),
    ]
