# Generated by Django 3.1.14 on 2022-09-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_auto_20220918_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='devSheet',
            new_name='developmentSheet',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='prodSheet',
            new_name='productionSheet',
        ),
    ]
