# Generated by Django 3.1.14 on 2023-01-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0009_auto_20221221_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlistStatus',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Private', 'Private'), ('Deleted', 'Deleted')], default='', max_length=20),
        ),
    ]
