# Generated by Django 3.1.14 on 2023-01-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0010_playlist_playliststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='localized',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='thumbnails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
