# Generated by Django 3.1.7 on 2021-03-08 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0002_auto_20210307_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='addDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='channelId',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='channel',
            name='channelStatus',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Deleted', 'Deleted')], max_length=20),
        ),
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='publishedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='subscriberCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
