# Generated by Django 3.1.7 on 2021-03-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20210307_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='publishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscriberCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
