# Generated by Django 3.1.7 on 2021-03-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_auto_20210308_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='wiki',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
