# Generated by Django 3.2.4 on 2021-11-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0013_auto_20211119_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channelId',
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
