# Generated by Django 3.2.4 on 2022-08-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0014_auto_20211120_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.AddField(
            model_name='channel',
            name='bannerExternalUrl',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='channel',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='channel',
            name='customUrl',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='channel',
            name='defaultLanguage',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='channel',
            name='hiddenSubscriberCount',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='localized',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='relatedPlaylists',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='thumbnails',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channelStatus',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Deleted', 'Deleted')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='publishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscriberCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='videoCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='viewCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='wiki',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
