# Generated by Django 3.2.4 on 2022-08-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0015_auto_20220731_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='localized',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='channel',
            name='relatedPlaylists',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='channel',
            name='thumbnails',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
