# Generated by Django 3.2.4 on 2022-08-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
        ('collectives', '0001_initial'),
        ('channels', '0017_auto_20220816_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='collective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collectives.collective'),
        ),
        migrations.AddField(
            model_name='channel',
            name='contributors',
            field=models.ManyToManyField(blank=True, default=[], to='contributors.Contributor'),
        ),
    ]
