# Generated by Django 3.1.14 on 2022-09-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20220918_1424'),
        ('channels', '0019_alter_channel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='devSheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels_dev_sheet', to='sheets.sheet'),
        ),
        migrations.AddField(
            model_name='channel',
            name='prodSheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels_prod_sheet', to='sheets.sheet'),
        ),
    ]
