# Generated by Django 3.1.14 on 2023-01-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0022_auto_20221221_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='localized',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='relatedPlaylists',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='thumbnails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
