# Generated by Django 3.2.18 on 2023-04-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0012_auto_20230115_1743'),
        ('sheets', '0006_auto_20230115_1743'),
        ('channels', '0024_auto_20230115_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='developmentChangelogSpreadsheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels_dev_changelog_spreadsheet', to='sheets.spreadsheet'),
        ),
        migrations.AddField(
            model_name='channel',
            name='developmentUndocumentedRipsPlaylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels_dev_undocumented_rips_playlist', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='channel',
            name='productionChangelogSpreadsheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels_prod_changelog_spreadsheet', to='sheets.spreadsheet'),
        ),
        migrations.AddField(
            model_name='channel',
            name='productionUndocumentedRipsPlaylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels_prod_undocumented_rips_playlist', to='playlists.playlist'),
        ),
    ]
