# Generated by Django 4.2.17 on 2026-04-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0027_channel_channeltype'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['publishedAt'], name='channels_ch_publish_e6eb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['title'], name='channels_ch_title_61162c_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['subscriberCount'], name='channels_ch_subscri_bca21a_idx'),
        ),
    ]
