# Generated by Django 3.2.4 on 2022-08-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
